# Generated by Django 6.0.6 on 2026-06-08 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('diretor', models.CharField(blank=True, max_length=255)),
                ('ano', models.PositiveIntegerField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, max_length=100)),
                ('nota', models.PositiveSmallIntegerField(help_text='Nota de 1 a 10')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
